version: "3.9"
services: 
    node:
        image: node:16.6.0-buster-slim
        container_name: sieve_ts
        volumes: 
            - ./src:/usr/src
        working_dir: /usr/src
        tty: true
        # command: bash -c 'npm ci && npm run build'