version: "3.9"
services: 
    rust:
        image: rust:1.54.0-buster
        container_name: sieve_rust
        volumes: 
            - ./projects:/projects
        working_dir: /projects
        tty: true
        user: ${USER_ID}:${GROUP_ID}